project_id = "xfswfetxfqhgvpwlhfce"

[functions.run-reconciliation]
verify_jwt = false

[functions.run-review]
verify_jwt = false

[functions.run-batch-review]
verify_jwt = false

[functions.trigger-review]
verify_jwt = false

[functions.review-callback]
verify_jwt = false