project_id = "xfswfetxfqhgvpwlhfce"

[functions.quickbooks-callback]
verify_jwt = false

[functions.run-reconciliation]
verify_jwt = false

[functions.run-review]
verify_jwt = false

[functions.run-batch-review]
verify_jwt = false

[functions.quickbooks-token-refresh]
verify_jwt = false

[functions.quickbooks-health-check]
verify_jwt = false

[functions.trigger-review]
verify_jwt = false

[functions.review-callback]
verify_jwt = false