project_id = "xfswfetxfqhgvpwlhfce"

[functions.quickbooks-callback]
verify_jwt = false

[functions.run-reconciliation]
verify_jwt = false

[functions.quickbooks-token-refresh]
verify_jwt = false

[functions.quickbooks-health-check]
verify_jwt = false